Traceback (most recent call last):
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/smanikka/miniforge3/envs/rl/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def func(x):
    return x**3 + x**2

node_in = make_node("V:node_in:0.5:m")
node_out = make_node("V:node_out", units="m")

f = Function(
    name="f",
    func=func,
    parents=node_in,
    children=node_out
)
print(f)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 4>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mfunc[39m(x):
[1;32m      2[0m     [38;5;28;01mreturn[39;00m x[38;5;241m*[39m[38;5;241m*[39m[38;5;241m3[39m [38;5;241m+[39m x[38;5;241m*[39m[38;5;241m*[39m[38;5;241m2[39m
[0;32m----> 4[0m node_in [38;5;241m=[39m [43mmake_node[49m([38;5;124m"[39m[38;5;124mV:node_in:0.5:m[39m[38;5;124m"[39m)
[1;32m      5[0m node_out [38;5;241m=[39m make_node([38;5;124m"[39m[38;5;124mV:node_out[39m[38;5;124m"[39m, units[38;5;241m=[39m[38;5;124m"[39m[38;5;124mm[39m[38;5;124m"[39m)
[1;32m      7[0m f [38;5;241m=[39m Function(
[1;32m      8[0m     name[38;5;241m=[39m[38;5;124m"[39m[38;5;124mf[39m[38;5;124m"[39m,
[1;32m      9[0m     func[38;5;241m=[39mfunc,
[1;32m     10[0m     parents[38;5;241m=[39mnode_in,
[1;32m     11[0m     children[38;5;241m=[39mnode_out
[1;32m     12[0m )

[0;31mNameError[0m: name 'make_node' is not defined
NameError: name 'make_node' is not defined

